on:
  issue_comment:
    types: [created]
name: Commented Pull Request
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    outputs:
      before_sha: ${{ steps.before.outputs.sha }}
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Get Initial HEAD
        id: before
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Pull Request Validator
        uses: ScoopInstaller/GithubActions@main
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  biome-format:
    name: Biome Format
    needs: pullRequestHandler
    uses: ./.github/workflows/biome-filter.yml
    with:
      before_sha: ${{ needs.pullRequestHandler.outputs.before_sha }}
      push_branch: ${{ github.ref }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
