on:
  issues:
    types: [opened, labeled]
name: Issue
jobs:
  issueHandler:
    name: Issue Handler
    runs-on: windows-latest
    permissions:
      contents: write
    outputs:
      before_sha: ${{ steps.before.outputs.sha }}
      after_sha: ${{ steps.after.outputs.sha }}
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Get Initial HEAD
        id: before
        shell: pwsh
        run: echo "sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
      - name: Issue Handler
        uses: ScoopInstaller/Scoop-GithubActions@main
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Final HEAD
        id: after
        shell: pwsh
        run: echo "sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT

  biome-format:
    name: Biome Format
    needs: issueHandler
    uses: ./.github/workflows/biome-filter.yml
    with:
      before_sha: ${{ needs.issueHandler.outputs.before_sha }}
      checkout_ref: ${{ needs.issueHandler.outputs.after_sha }}
      push_branch: ${{ github.ref }}
