on:
  pull_request_target:
    types: [opened]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Pull Request Validator
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install required tools
        run: |
          pip install git-filter-repo
          npm install -g @biomejs/biome
      - name: Run Filter Repo
        shell: pwsh
        env:
          BIOME_CONFIG: ${{ github.workspace }}/biome.json
        run: |
          $FixedConfig = $env:BIOME_CONFIG.Replace('\', '/')   
          git update-ref refs/BEFORE ${{ github.base_ref }}       
          git filter-repo --force `
            --refs refs/BEFORE..HEAD `
            --replace-message .github/git-filter.txt `
            --file-info-callback "
            import subprocess
            
            if not filename.startswith(b'bucket/') or not filename.endswith(b'.json'):
                return (filename, mode, blob_id)

            print(f'--- Checking: {filename.decode()} ---')

            if blob_id in value.data:
                return (filename, mode, value.data[blob_id])

            try:
                contents = value.get_contents_by_identifier(blob_id)

                process = subprocess.run(
                    ['biome', 'format', '--stdin-file-path', filename.decode(), '--config-path', '$FixedConfig'],
                    input=contents,
                    capture_output=True,
                    check=True,
                    shell=True
                )

                if process.stdout and process.stdout != contents:
                    print(f'      [FORMATTED] {filename.decode()}')
                    new_blob_id = value.insert_file_with_contents(process.stdout)
                    value.data[blob_id] = new_blob_id
                    return (filename, mode, new_blob_id)
                else:
                    print(f'      [NO CHANGE] {filename.decode()}')

            except Exception as e:
                print(f'      [ERROR] {filename.decode()}: {str(e)}')
                pass

            return (filename, mode, blob_id)
            "
          git update-ref -d refs/BEFORE
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
