on:
  pull_request_target:
    types: [opened]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    permissions:
      pull-requests: write
    outputs:
      before_sha: ${{ steps.before.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get Initial HEAD
        id: before
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Pull Request Validator
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  biome-format:
    name: Biome Format
    needs: pullRequestHandler
    uses: ./.github/workflows/biome-filter.yml
    with:
      before_sha: ${{ needs.pullRequestHandler.outputs.before_sha }}
      push_branch: ${{ github.head_ref }}
      checkout_ref: ${{ github.head_ref }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
