on:
  schedule:
    - cron: '2 */2 * * *'
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Initial HEAD
        run: git update-ref refs/BEFORE $(git rev-parse HEAD)
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
      - name: Install required tools
        run: |
          pip install git-filter-repo
          npm install -g @biomejs/biome
      - name: Run Filter Repo
        run: |
          CONFIG_PATH="$(pwd)/biome.json"
          git filter-repo --force `
            --refs refs/BEFORE..HEAD `
            --replace-message .github/git-filter.txt `
            --blob-callback "
            import subprocess

            target_exts = [b'.json']
            config_file = '$CONFIG_PATH'

            if any(metadata.filename.endswith(ext) for ext in target_exts):
                try:
                    process = subprocess.run(
                        ['biome', 'format', '--stdin-file-path', metadata.filename.decode(), '--config-path', config_file],
                        input=blob.data,
                        capture_output=True,
                        check=True
                    )
                    if process.stdout:
                        blob.data = process.stdout
                except Exception:
                    pass
            "
          git update-ref -d refs/BEFORE
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
