on:
  schedule:
    - cron: '2 * * * *'
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    permissions:
      contents: write
    outputs:
      before_sha: ${{ steps.before.outputs.sha }}
      after_sha: ${{ steps.after.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Initial HEAD
        id: before
        shell: pwsh
        run: echo "sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
      - name: Get Final HEAD
        id: after
        shell: pwsh
        run: echo "sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT

  biome-format:
    name: Biome Format
    needs: excavate
    uses: ./.github/workflows/biome-filter.yml
    with:
      before_sha: ${{ needs.excavate.outputs.before_sha }}
      checkout_ref: ${{ needs.excavate.outputs.after_sha }}
      push_branch: ${{ github.ref }}
